name: Reusable Release Notes Generator

on:
  workflow_dispatch:
    inputs:
      from-tag:
        description: '開始タグ (指定しない場合は最初のコミットから)'
        required: false
        type: string
      to-tag:
        description: '終了タグ (指定しない場合は最後のコミットまで)'
        required: false
        type: string
  workflow_call:
    inputs:
      from-tag:
        description: '開始タグ (指定しない場合は最初のコミットから)'
        required: false
        type: string
      to-tag:
        description: '終了タグ (指定しない場合は最後のコミットまで)'
        required: false
        type: string
      commit-message-format:
        description: 'コミットメッセージのフォーマット https://git-scm.com/docs/pretty-formats'
        required: false
        type: string
        default: '- %s (%h)'
    outputs:
      notes:
        description: '生成されたリリースノート'
        value: ${{ jobs.generate-notes.outputs.notes }}

jobs:
  generate-notes:
    runs-on: ubuntu-latest
    outputs:
      notes: ${{ steps.release-notes.outputs.notes }}
    env:
      FILTER_CONDITION: "fix|feat"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine range
        id: determine-range
        run: |
          echo "指定されたタグを確認しています..."
          # 開始タグが空の場合、最初のコミットのハッシュを取得
          if [ -z "${{ inputs.from-tag }}" ]; then
            from_commit=$(git rev-list --max-parents=0 HEAD)  # 最初のコミットを取得
            echo "開始タグが未指定のため、最初のコミット (${from_commit}) を開始点として使用します。"
          else
            from_commit="${{ inputs.from-tag }}"
            echo "指定された開始タグ: ${from_commit}"
          fi
          
          if [ -z "${{ inputs.to-tag }}" ]; then
            to_commit="HEAD"
            echo "終了タグが未指定のため、HEAD (${to_commit}) を終了点として使用します。"
          else
            to_commit="${{ inputs.to-tag }}"
            echo "指定された終了タグ: ${to_commit}"
          fi
          
          echo "::set-output name=from_commit::$from_commit"
          echo "::set-output name=to_commit::$to_commit"

      - name: Generate filtered release notes
        id: release-notes
        run: |
          echo "取得中のコミット範囲:"
          echo "開始: ${{ steps.determine-range.outputs.from_commit }}"
          echo "終了: ${{ steps.determine-range.outputs.to_commit }}"
          echo "フィルタ条件: $FILTER_CONDITION"

          notes=$(git log ${{ steps.determine-range.outputs.from_commit }}..${{ steps.determine-range.outputs.to_commit }} --pretty='format:"${{ inputs.commit-message-format }}"' | grep -iE "$FILTER_CONDITION" || echo "一致するコミットがありません")

          echo "::group::Notebook Contents"
          echo "$notes"
          echo "::endgroup::"
          echo "::set-output name=notes::$notes"