name: (Test) Release Notes Generator

on:
  workflow_dispatch:
    inputs:
      from-tag:
        description: 'Start tag (if not specified, the first commit is used)'
        required: false
        type: string
      to-tag:
        description: 'End tag (if not specified, the latest commit is used)'
        required: false
        type: string
      commit-message-format:
        description: 'Commit message format. See https://git-scm.com/docs/pretty-formats'
        required: false
        type: string
        default: "- %s by %cn (%h)"
      derive-from-tag:
        description: "true = Automatically determine from-tag by looking at previous tags in the repository. false = Do not set it automatically."
        required: false
        default: true
        type: boolean

jobs:
  release-notes:
    uses: ./.github/workflows/reusable-release-notes.yaml
    with:
      from-tag: ${{ inputs.from-tag }}
      to-tag: ${{ inputs.to-tag }}
      commit-message-format: ${{ inputs.commit-message-format }}
      commit-id: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
      derive-from-tag: ${{ inputs.derive-from-tag }}

  print:
    needs: [ release-notes ]
    runs-on: ubuntu-22.04
    steps:
      - name: Echo release notes
        run: |
          notes="${{ needs.release-notes.outputs.notes }}"
          IFS=$'\n'
          echo "::notice::Release Note:
          for line in $notes; do
          echo "::notice::$line"
          done